### ISSUE TITLE
I dont really understand

### ISSUE THREAD

**Issue by Powtaitoe** [jcbrockschmidt/scraptf-auto-raffle-util#1]
Hey, new person to scripting here. I already installed mechanize, wheel, python and all those stuff already. I used the editcookie plugin and exported my cookies to the cookie.txt. I don't know what LWP Perl format is though... I ran enter_raffles.py in terminal, by using `python enter_raffles.py` and it says :

Traceback (most recent call last):
  File "enter_raffles.py", line 68, in <module>
    main()
  File "enter_raffles.py", line 50, in main
    entered_cnt = try_enter_all_raffles(br, delay=DELAY)
  File "My file directory", line 210, in try_enter_all_raffles
    for raffle_id, entered in reversed(raffles):
TypeError: 'bool' object is not reversible

What's wrong?

**Comment by Kaczka212** [comment]
idk i have same problem
